### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by anno192** [princeton-vl/oasis#1]
Thanks for open-sourcing your brilliant job!

How should I generate the texturized 3D model using the model's prediction? Are there any tools or code I could use for that? Any help would be great!

**Comment by wfchen-umich** [comment]
Hi, 
Thank you for your interest in our dataset. I have uploaded a script to https://github.com/princeton-vl/oasis/blob/master/utils/vis_mesh.py. Please check.

**Comment by anno192** [comment]
Thanks a lot for your reply!
