### ISSUE TITLE
Wrong tensorboard logs

### ISSUE THREAD

**Issue by leejaeyong7** [princeton-vl/oasis#11]
Hi,

Thanks for open sourcing the project. 

I was trying to train the model with small modification, and figured out that the logging function have a typo in the repository:
https://github.com/princeton-vl/oasis/blob/master/experiments/normal_estimation/train.py#L236
https://github.com/princeton-vl/oasis/blob/master/experiments/normal_estimation/train.py#L238

The VAL < 22.5 and < 30 is actually reporting training accuracy.

Thanks!

**Comment by wfchen-umich** [comment]
Hi,
Good catch. Thanks for letting us know!
