### ISSUE TITLE
Fast downloading gdrive datasets to remote server?

### ISSUE THREAD

**Issue by XiaoSongXS** [princeton-vl/oasis#2]
Hi! 

Thanks for the wonderful dataset. I'm wondering if there's any way I can download the dataset from gdrive faster to a remote server? I have tried few script including [gdrive](https://github.com/prasmussen/gdrive), [wget](https://unix.stackexchange.com/questions/136371/how-to-download-a-folder-from-google-drive-using-terminal)  but those scripts either is deprecated or don't work for the large file like dataset. 

Thanks
Xiao

**Comment by wfchen-umich** [comment]
Hi Xiao,

Thanks for your interest in our dataset. 
I suggest you to use rclone (https://rclone.org/) to download it.

**Comment by XiaoSongXS** [comment]
Thanks!
