### ISSUE TITLE
Relative normal evaluation

### ISSUE THREAD

**Issue by Ainaz99** [princeton-vl/oasis#4]
Hi,

I'm trying to do relative normal evaluation on OASIS, but I don't see where the `rel_normal_pair_val.csv` comes from.

Thanks for your response.

**Comment by wfchen-umich** [comment]
Hi,

Thanks for bringing this up. The file can be found in https://drive.google.com/file/d/1LRfITcQ8va6m1S7emlCAGC11iEemxe9S/view?usp=sharing

Let me know if it is working.

**Comment by Ainaz99** [comment]
Thanks @wfchen-umich, it works.

I just want to know if the results for relative normals in the paper reported on all the images in this csv file or a subset of them.
Also, the results for the absolute normals, are they reported on the whole validation set (as in OASIS_val.csv) or just a subset?

**Comment by wfchen-umich** [comment]
HI, 

The results reported in the paper are on the TEST set. Please follow the instructions listed on https://github.com/princeton-vl/oasis/tree/master/experiments/normal_estimation to evaluate your TEST results on the evaluation server.

**Comment by Ainaz99** [comment]
Is the evaluation server working? It seems to be down.

**Comment by wfchen-umich** [comment]
Hi, it is back online, could you try it? Let me know if there are further issues.

**Comment by alexsax** [comment]
I think there is a compatibility issue with Mac OS X in the online form. On Mac OSX, the OS file picker does not allow you to select .tar.gz files, so files cannot be uploaded (see [here](https://bugs.chromium.org/p/chromium/issues/detail?id=521781)). A workaround is to change the `accept=.tar.gz` field to `accept=.gz`.

If we want to evaluate multiple baselines in a way so that we can compare to the original OASIS paper, is there a way to test more than 2 models per 10 days, and/or submit the .tar.gz files programmatically?

**Comment by wfchen-umich** [comment]
Hi,
I have changed the accept=.tar.gz field to accept=.gz, let me know if it works?
Right now we don't allow submit programmatically.

**Comment by alexsax** [comment]
Yes that fixes the client-side problem, but after upload the server returns the following error:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/5157485/111274222-fb05b580-85f1-11eb-99e6-5d8b7efa06ea.png">

**Comment by lahavlipson** [comment]
Hi, we are addressing the Internal Server Error and will issue a fix shortly. We'll update this thread as soon as we have an update.

**Comment by alexsax** [comment]
Hi Lahav--thanks for the heads up. Any chance you can share an ETA of when we should be able to submit results to the server (or could send the `.tar.gz` for submission in some other way)?

**Comment by lahavlipson** [comment]
You can send the .tar.gz file to oasis-support@lists.cs.princeton.edu and we can evaluate your submission right away. The submission page should be fixed in a couple of days and we will keep this issue open and updated until then.

**Comment by lahavlipson** [comment]
We have added a python script [upload_to_benchmark.py](https://github.com/princeton-vl/oasis/blob/master/upload_to_benchmark.py) which can be used to upload to the OASIS benchmark [#6]. We have added usage instructions to the website and README. This python script should provide a better upload experience and can be easily run on a headless machine.
